### PR TITLE
Remove mongodb dependency

### PR DESCRIPTION
**Pull request by cavedweller**
This isn't actually used anywhere and just creates cruft

### CODE REVIEW

**Comment by tejacques** [comment]
@mmaxim can you take a look as this before it's merged? It looks good to me.

**Comment by mmaxim** [comment]
Is there something in particular that this is making difficult? I'd like a little more context before merging.

**Comment by cavedweller** [comment]
I've made okws/sfslite submodules for oksrc. Getting the bson/libmongo to build in this new setup would slightly increase the complexity of the build system. Since we don't use them, and don't have plans to use them, I figured it would be easier to remove the dependencies.

**Comment by mmaxim** [comment]
Can we just de-submodule `okmongo` instead and bring it into the okws repo? I'd just hate to drop all of that code.

**Comment by tejacques** [comment]
I don't really see an advantage to keeping it in okws -- why don't we just move it into `okmongo` if we're concerned about the code just disappearing?

**Comment by tejacques** [comment]
@mmaxim: We pulled out the other changes into oksrc / okmongo which are sitting in PRs waiting for this to land. Going to merge this now.

**Comment by tejacques** [comment]
If something unexpected happens it's pretty easy to revert this, too

**Pull request merged**
