### PR TITLE
Okmongo

### PR DESCRIPTION
**Pull request by till-varoquaux**
Add support for mongo in okws

### CODE REVIEW

**Comment by mmaxim** [comment]
I'll merge this, but please bump the OKWS version as part of this. Thanks!

**Comment by mmaxim** [comment]
Change to 3.1.32.0

**Comment by till-varoquaux** [comment]
Done

**Comment by till-varoquaux** [comment]
Fixed. Once and for all. okws_sfs.h is now auto-generated.

**Pull request merged**
